"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { authConfigured } from "@/lib/admin/applications-shared";
import { getProfile } from "@/lib/auth";
import { logAudit } from "@/lib/admin/audit";

export async function advanceApplicationStage(id: string, stage: string) {
  if (!authConfigured) return;
  const supabase = await createClient();
  const profile = await getProfile();
  const { data: prev } = await supabase
    .from("applications")
    .select("stage")
    .eq("id", id)
    .single();
  await supabase.from("applications").update({ stage }).eq("id", id);
  await supabase.from("application_events").insert({
    application_id: id,
    actor_id: profile?.id,
    type: "stage_change",
    from_stage: prev?.stage,
    to_stage: stage,
    body: `Moved to ${stage}`,
  });
  await logAudit({ action: "stage_change", target_type: "application", target_id: id, detail: `${prev?.stage ?? "?"} → ${stage}` });
  revalidatePath("/admin", "layout");
}

export async function addApplicationNote(id: string, body: string) {
  if (!authConfigured || !body.trim()) return;
  const supabase = await createClient();
  const profile = await getProfile();
  await supabase.from("application_events").insert({
    application_id: id,
    actor_id: profile?.id,
    type: "note",
    body: body.trim(),
  });
  revalidatePath("/admin", "layout");
}

/**
 * Convert an enquiry (registration) into a student + application. Creates the
 * student master from the lead's contact, then one application per selected
 * track. No-op in dev (mock).
 */
export async function createApplicationFromLead(leadId: string) {
  if (!authConfigured) return;
  const supabase = await createClient();
  const profile = await getProfile();
  const { data: reg } = await supabase
    .from("registrations")
    .select("*")
    .eq("id", leadId)
    .single();
  if (!reg) return;

  const isInternational = (reg.nationality ?? "").toLowerCase() !== "my";

  // Resolve the referring agent (if any) from the agent_code on the enquiry.
  let agentId: string | null = null;
  let agentName: string | null = null;
  if (reg.agent_code) {
    const { data: ag } = await supabase
      .from("profiles")
      .select("id, full_name")
      .eq("agent_code", reg.agent_code)
      .eq("role", "agent")
      .maybeSingle();
    if (ag) {
      agentId = ag.id;
      agentName = ag.full_name;
    }
  }

  const { data: student } = await supabase
    .from("students")
    .insert({
      enquiry_id: reg.id,
      full_name: reg.full_name,
      email: reg.email,
      phone: reg.phone,
      whatsapp: reg.whatsapp,
      nationality: reg.nationality,
      date_of_birth: reg.dob ?? null,
      guardian: reg.details?.guardian ?? null,
      is_international: isInternational,
      agent_code: reg.agent_code,
      agent_id: agentId,
    })
    .select("id, passport_no")
    .single();
  if (!student) return;

  const tracks: string[] = reg.tracks ?? [];
  for (const track of tracks) {
    // Denormalised display fields keep list reads to a plain `select *`.
    // access_code is auto-generated by the DB default.
    await supabase.from("applications").insert({
      student_id: student.id,
      track,
      submitted_by: reg.agent_code ? "agent" : "staff",
      stage: "application",
      student_name: reg.full_name,
      student_email: reg.email,
      passport_no: student.passport_no,
      is_international: isInternational,
      agent_id: agentId,
      agent_name: agentName,
      // The staff member converting the lead becomes the handler (incentive).
      created_by: profile?.id ?? null,
      assigned_to: profile?.id ?? null,
    });
  }
  await logAudit({
    action: "application_created",
    target_type: "lead",
    target_id: reg.id,
    detail: `${reg.full_name} · ${tracks.join(", ")}`,
  });
  revalidatePath("/admin", "layout");
}
